# Generated by Django 6.0.1 on 2026-01-28 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0002_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "session"),
                name="unique_row_seat_session_for_ticket",
            ),
        ),
    ]
