# Generated by Django 6.0.1 on 2026-01-28 22:22

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planetarium", "0003_ticket_unique_row_seat_session_for_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.create_custom_path
            ),
        ),
    ]
